version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "ci"
    labels: []
    open-pull-requests-limit: 5
